# This playbook installs and starts the docker service 
# Install ansible on your linux machine: yum install ansible
# Make changes in the host file in /etc/ansible/hosts by adding instance details
# Make sure you have the key in the Network & Security -> keypair

#! /bin/env bash
#! PATH=$PATH:$HOME/.local/bin:$HOME/bin

-
  name: PB to install docker and start the docker
  hosts: production_server, webserver
  become: yes
  tasks:
    - name: code to install docker
      yum:
        name: docker
        state: present
    - name: start the docker service
      service:
        name:  docker
        state: started
