---
- name: To install boto and botocore packages
  become: yes
  hosts: webservers, production_server
  tasks:
  - name: Using pip module
    pip:
      name: ["boto", "botocore"]
      state: present

- name: Create an EC2 instance
  hosts: webservers, production_server
  gather_facts: False
  tasks:
    - name: Launch instance
      ec2:
        key_name: Ponnuvel
        instance_type: t2.micro
        image: ami-08e4e35cccc6189f4
        aws_access_key: "{aws_access_key}"
        aws_secret_key: "{aws_secret_key}"
        wait: true
        region: us-east-1

      register: ec2
    - name: Print ec2 vars
      debug: var=ec2
    - name: Get IP
      debug: var=ec2.instances[0].public_dns_name

    - pause: minutes=1
