# This playbook installs httpd and starts the httpd service on node1
# Install ansible on your linux machine: yum install ansible
# Make changes in the host file in /etc/ansible/hosts by adding instance details
# Make sure you have the key in the Network & Security -> keypair

#! /bin/env bash
#! PATH=$PATH:$HOME/.local/bin:$HOME/bin
-
  name: play to install httpd
  hosts: node1
  tasks:
    - name: use case of yum module
      yum:
        name: httpd
        state: present
-
  name: play to start httpd
  hosts: node1
  tasks:
    - name: use case of service module
      service:
        name: httpd
        state: started
